/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.vuw.ecs.swen225.gp20.application;

/**
 *
 * @author camilalis
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameCanvas = new javax.swing.JPanel();
        BoardCanvas = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        gameBotton = new javax.swing.JMenu();
        newGame = new javax.swing.JMenuItem();
        replay = new javax.swing.JMenuItem();
        fileBotton = new javax.swing.JMenu();
        loadBotton = new javax.swing.JMenuItem();
        saveBotton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 207, 18));

        GameCanvas.setBackground(new java.awt.Color(0, 208, 18));

        javax.swing.GroupLayout BoardCanvasLayout = new javax.swing.GroupLayout(BoardCanvas);
        BoardCanvas.setLayout(BoardCanvasLayout);
        BoardCanvasLayout.setHorizontalGroup(
            BoardCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        BoardCanvasLayout.setVerticalGroup(
            BoardCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GameCanvasLayout = new javax.swing.GroupLayout(GameCanvas);
        GameCanvas.setLayout(GameCanvasLayout);
        GameCanvasLayout.setHorizontalGroup(
            GameCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameCanvasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(BoardCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(484, Short.MAX_VALUE))
        );
        GameCanvasLayout.setVerticalGroup(
            GameCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameCanvasLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(BoardCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        gameBotton.setText("Game");

        newGame.setText("New Game");
        gameBotton.add(newGame);

        replay.setText("Replay");
        gameBotton.add(replay);

        jMenuBar1.add(gameBotton);

        fileBotton.setText("File");

        loadBotton.setText("Load JSON FILE");
        loadBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBottonActionPerformed(evt);
            }
        });
        fileBotton.add(loadBotton);

        saveBotton.setText("Save Game");
        saveBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBottonActionPerformed(evt);
            }
        });
        fileBotton.add(saveBotton);

        jMenuBar1.add(fileBotton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GameCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GameCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadBottonActionPerformed

    private void saveBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoardCanvas;
    private javax.swing.JPanel GameCanvas;
    private javax.swing.JMenu fileBotton;
    private javax.swing.JMenu gameBotton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem loadBotton;
    private javax.swing.JMenuItem newGame;
    private javax.swing.JMenuItem replay;
    private javax.swing.JMenuItem saveBotton;
    // End of variables declaration//GEN-END:variables
}
